name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: kevin-s31/actions/setup@feat/github-actions-color 
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Snyk monitor
      run: ls -l
      run: pwd
      run: snyk monitor --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
